"""
Workflow Monitoring Models
Database models for tracking n8n workflow executions and performance
"""

from sqlalchemy import Column, Integer, String, DateTime, JSON, ForeignKey, Float, Boolean
from sqlalchemy.orm import relationship
from datetime import datetime
from app.models.base import Base


class WorkflowExecution(Base):
    """Track individual workflow executions"""
    __tablename__ = "workflow_execution_monitoring"

    id = Column(Integer, primary_key=True, index=True)
    execution_id = Column(String(100), unique=True, index=True, nullable=False)
    workflow_id = Column(String(100), index=True)
    workflow_name = Column(String(200), index=True, nullable=False)

    # Associated lead
    lead_id = Column(Integer, ForeignKey("leads.id"), nullable=True, index=True)
    lead = relationship("Lead", back_populates="workflow_executions")

    # Execution status
    status = Column(String(50), index=True, default="running")  # running, success, failed, waiting_approval, cancelled
    mode = Column(String(50))  # manual, trigger, webhook, scheduled

    # Timing
    started_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    completed_at = Column(DateTime, nullable=True)
    duration_seconds = Column(Integer, nullable=True)

    # Execution details
    nodes_executed = Column(Integer, default=0)
    nodes_total = Column(Integer, default=0)
    current_node = Column(String(200), nullable=True)

    # Error handling
    has_errors = Column(Boolean, default=False)
    error_count = Column(Integer, default=0)
    errors = Column(JSON, nullable=True)  # List of error objects
    retry_count = Column(Integer, default=0)

    # Data
    input_data = Column(JSON, nullable=True)
    output_data = Column(JSON, nullable=True)

    # Metrics
    metrics = Column(JSON, nullable=True)  # Custom metrics per workflow

    # Metadata
    triggered_by = Column(String(100), nullable=True)
    version = Column(String(50), nullable=True)
    tags = Column(JSON, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<WorkflowExecution {self.workflow_name} - {self.status}>"


class WorkflowMetrics(Base):
    """Aggregated metrics for workflows"""
    __tablename__ = "workflow_metrics"

    id = Column(Integer, primary_key=True, index=True)
    workflow_name = Column(String(200), index=True, nullable=False)
    date = Column(DateTime, index=True, nullable=False)
    period = Column(String(20), default="daily")  # hourly, daily, weekly, monthly

    # Execution counts
    total_executions = Column(Integer, default=0)
    successful_executions = Column(Integer, default=0)
    failed_executions = Column(Integer, default=0)
    cancelled_executions = Column(Integer, default=0)

    # Success rate
    success_rate = Column(Float, default=0.0)  # Percentage

    # Timing metrics
    avg_duration_seconds = Column(Float, default=0.0)
    min_duration_seconds = Column(Integer, default=0)
    max_duration_seconds = Column(Integer, default=0)
    total_duration_seconds = Column(Integer, default=0)

    # Node metrics
    avg_nodes_executed = Column(Float, default=0.0)
    total_nodes_executed = Column(Integer, default=0)

    # Error metrics
    total_errors = Column(Integer, default=0)
    total_retries = Column(Integer, default=0)

    # Custom metrics
    custom_metrics = Column(JSON, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<WorkflowMetrics {self.workflow_name} - {self.date}>"


class WorkflowAlert(Base):
    """Alerts generated by workflow monitoring"""
    __tablename__ = "workflow_alerts"

    id = Column(Integer, primary_key=True, index=True)
    workflow_execution_id = Column(Integer, ForeignKey("workflow_execution_monitoring.id"), nullable=True)
    workflow_name = Column(String(200), index=True)

    # Alert details
    alert_type = Column(String(100), index=True, nullable=False)  # error, performance, timeout, rate_limit
    severity = Column(String(20), default="medium")  # low, medium, high, critical
    title = Column(String(500), nullable=False)
    message = Column(String(2000), nullable=False)

    # Resolution
    is_resolved = Column(Boolean, default=False, index=True)
    resolved_at = Column(DateTime, nullable=True)
    resolved_by = Column(String(100), nullable=True)
    resolution_notes = Column(String(2000), nullable=True)

    # Notification
    notification_sent = Column(Boolean, default=False)
    notification_sent_at = Column(DateTime, nullable=True)

    # Data
    alert_data = Column(JSON, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<WorkflowAlert {self.alert_type} - {self.severity}>"


class WorkflowApproval(Base):
    """Track approval gates in workflows"""
    __tablename__ = "legacy_workflow_approvals"

    id = Column(Integer, primary_key=True, index=True)
    workflow_execution_id = Column(Integer, ForeignKey("workflow_execution_monitoring.id"), nullable=False)
    lead_id = Column(Integer, ForeignKey("leads.id"), nullable=True)

    # Approval gate details
    gate_name = Column(String(200), nullable=False)  # plan_approval, demo_approval, video_approval
    gate_type = Column(String(100), default="manual")  # manual, automatic, conditional

    # Status
    status = Column(String(50), default="pending")  # pending, approved, rejected, timeout

    # Decision
    approved_by = Column(String(100), nullable=True)
    decision_at = Column(DateTime, nullable=True)
    decision_notes = Column(String(2000), nullable=True)

    # Timeout
    timeout_at = Column(DateTime, nullable=True)

    # Data for approval decision
    approval_data = Column(JSON, nullable=True)  # Data shown to approver

    # Webhook URL for approval
    approval_webhook_url = Column(String(500), nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<WorkflowApproval {self.gate_name} - {self.status}>"


class ABTestResult(Base):
    """Track A/B test results from workflows"""
    __tablename__ = "ab_test_results"

    id = Column(Integer, primary_key=True, index=True)
    test_name = Column(String(200), index=True, nullable=False)
    lead_id = Column(Integer, ForeignKey("leads.id"), nullable=False)

    # Test configuration
    variant = Column(String(50), index=True, nullable=False)  # A, B, C, etc.
    test_parameter = Column(String(200))  # What's being tested (voice_style, email_subject, etc.)
    variant_value = Column(String(500))  # Value for this variant

    # Assignment
    assigned_at = Column(DateTime, default=datetime.utcnow)

    # Metrics
    email_opened = Column(Boolean, default=False)
    email_opened_at = Column(DateTime, nullable=True)

    email_clicked = Column(Boolean, default=False)
    email_clicked_at = Column(DateTime, nullable=True)

    replied = Column(Boolean, default=False)
    replied_at = Column(DateTime, nullable=True)

    converted = Column(Boolean, default=False)
    converted_at = Column(DateTime, nullable=True)

    # Engagement metrics
    video_views = Column(Integer, default=0)
    video_watch_duration = Column(Integer, default=0)  # seconds
    demo_visits = Column(Integer, default=0)
    demo_time_spent = Column(Integer, default=0)  # seconds

    # Custom metrics
    custom_metrics = Column(JSON, nullable=True)

    # Metadata
    test_metadata = Column(JSON, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<ABTestResult {self.test_name} - Variant {self.variant}>"


class WorkflowReport(Base):
    """Store generated workflow reports"""
    __tablename__ = "workflow_reports"

    id = Column(Integer, primary_key=True, index=True)
    report_type = Column(String(100), index=True, nullable=False)  # daily, weekly, monthly, custom
    report_name = Column(String(200), nullable=False)

    # Time period
    start_date = Column(DateTime, nullable=False)
    end_date = Column(DateTime, nullable=False)

    # Report data
    summary = Column(JSON, nullable=False)  # High-level summary
    detailed_metrics = Column(JSON, nullable=False)  # Detailed metrics

    # Charts/visualizations data
    charts_data = Column(JSON, nullable=True)

    # Generated files
    pdf_path = Column(String(500), nullable=True)
    html_path = Column(String(500), nullable=True)

    # Distribution
    sent_to = Column(JSON, nullable=True)  # List of email addresses
    sent_at = Column(DateTime, nullable=True)

    # Metadata
    generated_by = Column(String(100), default="system")

    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<WorkflowReport {self.report_name} - {self.report_type}>"
