// Script viewer with scenes and timestamps - Journey 3

import { useState } from 'react'
import { ClockIcon, PlayIcon } from '@heroicons/react/24/outline'
import { VideoScript } from '@/mocks/videos.mock'

interface ScriptViewerProps {
  script: VideoScript
  onSeekTo?: (timestamp: number) => void
}

export default function ScriptViewer({ script, onSeekTo }: ScriptViewerProps) {
  const [selectedScene, setSelectedScene] = useState<string | null>(null)

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60)
    const secs = seconds % 60
    return `${mins}:${secs.toString().padStart(2, '0')}`
  }

  return (
    <div className="space-y-6">
      {/* Script Header */}
      <div className="card p-6">
        <div className="flex items-start justify-between">
          <div className="flex-1">
            <h3 className="text-lg font-semibold text-dark-text-primary mb-2">
              Video Script
            </h3>
            <div className="flex items-center gap-4 text-sm text-dark-text-muted">
              <span className="flex items-center gap-1">
                <ClockIcon className="w-4 h-4" />
                {formatTime(script.total_duration)} total
              </span>
              <span>{script.word_count} words</span>
              <span>{script.scenes.length} scenes</span>
              <span className="capitalize">Generated by {script.generated_by}</span>
            </div>
          </div>
        </div>

        {/* Full Script */}
        <div className="mt-4 p-4 bg-dark-surface rounded-lg border border-dark-border">
          <p className="text-sm text-dark-text-secondary leading-relaxed whitespace-pre-wrap">
            {script.content}
          </p>
        </div>
      </div>

      {/* Scenes Timeline */}
      <div className="card p-6">
        <h3 className="text-lg font-semibold text-dark-text-primary mb-4">
          Scenes & Timeline
        </h3>
        <div className="space-y-3">
          {script.scenes.map((scene, index) => (
            <div
              key={scene.id}
              className={`p-4 rounded-lg border-2 transition-all cursor-pointer ${
                selectedScene === scene.id
                  ? 'border-terminal-500 bg-terminal-500/10'
                  : 'border-dark-border hover:border-terminal-600 bg-dark-surface'
              }`}
              onClick={() => {
                setSelectedScene(scene.id)
                onSeekTo?.(scene.timestamp)
              }}
            >
              <div className="flex items-start gap-4">
                {/* Scene number */}
                <div className="flex-shrink-0">
                  <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold ${
                    selectedScene === scene.id
                      ? 'bg-terminal-500 text-white'
                      : 'bg-dark-border text-dark-text-muted'
                  }`}>
                    {index + 1}
                  </div>
                </div>

                {/* Scene content */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-3 mb-2">
                    <span className="text-xs font-mono font-semibold text-terminal-400">
                      {formatTime(scene.timestamp)} - {formatTime(scene.timestamp + scene.duration)}
                    </span>
                    <span className="text-xs text-dark-text-muted">
                      ({scene.duration}s)
                    </span>
                    {scene.screen_section && (
                      <span className="text-xs px-2 py-0.5 bg-blue-500/20 text-blue-400 rounded-full">
                        {scene.screen_section}
                      </span>
                    )}
                  </div>

                  {/* Narration */}
                  <p className="text-sm text-dark-text-primary mb-2 leading-relaxed">
                    {scene.narration}
                  </p>

                  {/* Action */}
                  <div className="flex items-start gap-2 text-xs">
                    <span className="text-dark-text-muted font-medium">Action:</span>
                    <span className="text-dark-text-secondary italic">{scene.action}</span>
                  </div>
                </div>

                {/* Play button */}
                {onSeekTo && (
                  <button
                    onClick={(e) => {
                      e.stopPropagation()
                      onSeekTo(scene.timestamp)
                    }}
                    className="flex-shrink-0 p-2 text-dark-text-secondary hover:text-terminal-400 hover:bg-terminal-500/10 rounded transition-colors"
                    title="Play from here"
                  >
                    <PlayIcon className="w-5 h-5" />
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Script Metadata */}
      <div className="card p-6">
        <h3 className="text-lg font-semibold text-dark-text-primary mb-4">
          Script Details
        </h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div>
            <p className="text-xs text-dark-text-muted mb-1">Total Duration</p>
            <p className="text-lg font-semibold text-dark-text-primary">
              {formatTime(script.total_duration)}
            </p>
          </div>
          <div>
            <p className="text-xs text-dark-text-muted mb-1">Word Count</p>
            <p className="text-lg font-semibold text-dark-text-primary">
              {script.word_count}
            </p>
          </div>
          <div>
            <p className="text-xs text-dark-text-muted mb-1">Scenes</p>
            <p className="text-lg font-semibold text-dark-text-primary">
              {script.scenes.length}
            </p>
          </div>
          <div>
            <p className="text-xs text-dark-text-muted mb-1">Avg Scene Length</p>
            <p className="text-lg font-semibold text-dark-text-primary">
              {(script.total_duration / script.scenes.length).toFixed(1)}s
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
